name: ontest-pr

on:
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: onctl

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Install ontest
        run: |
          wget https://github.com/onkube/homebrew-tap/releases/download/v0.0.27/ontest-linux-amd64.tar.gz
          tar -xzf ontest-linux-amd64.tar.gz
          sudo mv ontest /usr/local/bin
      - name: ls
        run: |
          ontest ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      - name: deploy
        run: |
          cd $GITHUB_WORKSPACE
          ls -al
          ontest deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1

