name: ontest-pr

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize, closed]


jobs:
  preview-env:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'dummy'
      - name: Install ontest
        run: |
          wget https://github.com/onkube/homebrew-tap/releases/download/v0.0.33/ontest-linux-amd64.tar.gz
          tar -xzf ontest-linux-amd64.tar.gz
          chmod +x ontest
          sudo mv ontest /usr/local/bin/ontest
          # wget https://github.com/onkube/homebrew-tap/releases/download/test/ontest-linux
          # chmod +x ontest-linux
          # sudo mv ontest-linux /usr/local/bin/ontest

          ontest version
      - name: ls
        run: |
          echo $SSH_PUBLIC_KEY > ~/.ssh/id_rsa.pub
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      - name: deploy
        if: github.event.action != 'closed'
        run: |
          cd $GITHUB_WORKSPACE
          ONTEST_LOG=DEBUG ontest deploy -p 80
          ssh-keyscan $(cat ip.txt) >> ~/.ssh/known_hosts
          DOCKER_HOST=ssh://ubuntu@$(cat ip.txt) docker compose up -d --build
          gh pr comment ${{ github.event.pull_request.number }} -b "Deployed to $(cat ontest-deploy.json | jq -r '.public_url')"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          GH_TOKEN: ${{ github.token }}
      - name: destroy
        if: github.event.action == 'closed'
        run: |
          cd $GITHUB_WORKSPACE
          ONTEST_LOG=DEBUG ontest delete self
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          GH_TOKEN: ${{ github.token }}
